### ISSUE TITLE
Panic when opened on folder (on Windows at least)

### ISSUE THREAD

**Issue by Ytrog** [tuxxy/entropy#2]
```ps1
> entropy .
```

```
thread 'main' panicked at 'Couldn't open the file at the provided path.: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\entropy-lib-1.0.2\src/main.rs:21:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mikemadden42** [comment]
I see a similar issue on macOS.  I'm betting that you can only pass a filename, not a directory.

```
$ entropy .
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', src/lib.rs:20:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```bash
$ entropy --help
entropy-lib 1.0.2
tux <me@johnpacific.com>
A utility to calculate Shannon entropy of a given file

USAGE:
    entropy [OPTIONS] <FILEPATH>

ARGS:
    <FILEPATH>    The target file to measure

OPTIONS:
    -h, --help              Print help information
    -m, --metric-entropy    Returns metric entropy instead of Shannon entropy
    -V, --version           Print version information
```

**Comment by Ytrog** [comment]
Interesting. Maybe it should check if it is a directory and handle that more gracefully 🤔
